services:
  db:
    image: rethinkdb:2.4.3
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
    volumes:
      - ./rethinkdb/data:/data
  mqtt:
    image: eclipse-mosquitto:2.0.18
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
