services:
  redis:
    image: redis:7
    expose:
      - 6379:6379
  db:
    image: rethinkdb:2.4.3
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:28015:28015
      - 127.0.0.1:29015:29015
    volumes:
      - ./rethinkdb/data:/data
  mqtt:
    image: eclipse-mosquitto:2.0.18
    expose:
      # use `ports` when actually deploying
      # this is only for the expo demo where we need to port
      # forward from our local demo machine via SSH tunneling
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
    depends_on:
      - redis
  mqtt_listener:
    build: ./mosquitto
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - RETHINKDB_HOST=db
    depends_on:
      - mqtt
  backend:
    image: ghcr.io/noahcardoza/argus-backend:latest
    environment:
      - RETHINKDB_HOST=db
      - REDIS_DSN=redis://redis:6379/0
      - MQTT_HOST=mqtt
      - BREVO_API_KEY=${BREVO_API_KEY}
      - WEBSERVER_PROTOCOL=${WEBSERVER_PROTOCOL}
      - WEBSERVER_HOST=${WEBSERVER_HOST}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    expose:
      - 80:80
  celery_worker:
    image: ghcr.io/noahcardoza/argus-backend:latest
    command: celery --app=app.worker worker -l INFO
    volumes:
      - ./raw-elevation-cache:/root/.cache/elevation
      - ./elevation-cache:/app/.cache/elevation
    environment:
      - RETHINKDB_HOST=db
      - REDIS_DSN=redis://redis:6379/0
      - MQTT_HOST=mqtt
      - BREVO_API_KEY=${BREVO_API_KEY}
      - WEBSERVER_PROTOCOL=${WEBSERVER_PROTOCOL}
      - WEBSERVER_HOST=${WEBSERVER_HOST}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
  celery_beat:
    image: ghcr.io/noahcardoza/argus-backend:latest
    command: celery --app=app.worker beat -S redisbeat.RedisScheduler -l INFO
    environment:
      - RETHINKDB_HOST=db
      - REDIS_DSN=redis://redis:6379/0
      - MQTT_HOST=mqtt
      - BREVO_API_KEY=${BREVO_API_KEY}
      - WEBSERVER_PROTOCOL=${WEBSERVER_PROTOCOL}
      - WEBSERVER_HOST=${WEBSERVER_HOST}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
  frontend:
    build: ./frontend
    expose:
      - 80:80
  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - 0.0.0.0:443:443/udp
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - ./caddy_data_prod:/data
      - ./caddy_config_prod:/config
    environment:
      - FRONTEND_HOST=frontend:80
      - BACKEND_HOST=backend:80
    depends_on:
      - frontend
      - backend
